### ISSUE TITLE
Accounts object does not exist

### ISSUE THREAD

**Issue by netmobile** [recursivefaults/meteor-session-timeout#2]
I'm running into this issue after adding this package.  If I comment out the  validateLoginAttempt declaration, at least the module works.  Is there other dependencies, or what else am I missing?

Here's the error:

W20140506-17:53:18.792(-7)? (STDERR) TypeError: Object #<Object> has no method 'validateLoginAttempt'
W20140506-17:53:18.793(-7)? (STDERR)     at Package (packages/session-timeout/server/login_helper.coffee:2:33)

**Comment by recursivefaults** [comment]
Thanks for your interest in this package!

Are you using any of the standard accounts-ui packages? I believe that is where that method is expected to live. Let me know if that helps.

**Comment by netmobile** [comment]
I found out I'm using Meteor 7.0, which does not have that method for Accounts.  May be that's why.

**Comment by recursivefaults** [comment]
Good call @netmobile!

It looks like that particular hook was added in 0.7.2.

**Comment by recursivefaults** [comment]
I updated documentation to indicate the minimum version.
